---
# tasks file for laptop-ubu

- name: "ensure apt will work on this ubu system"
  command: apt-get install --reinstall python3-apt

- name: "Add user kurt to sudo"
  lineinfile:
    path: "/etc/sudoers.d/{{local_user}}"
    line: '{{local_user}} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'


- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: "add PPAs"
  apt_repository:
    repo: '{{ item }}'
    state: present
    update_cache: True
    validate_certs: False
  with_items:RE
    - ppa:stebbins/handbrake-releases
    - ppa:audio-recorder/ppa

- name: "install handbrake"
  apt:
    state: latest
    name: "{{ pkgs }}"
  vars:
    pkgs:
      - handbrake-gtk
      - handbrake-cli
      - audio-recorder
