---

- name: "Create the /opt/tmp directory structure if it does not exist"
  ansible.builtin.file:
    path: "/opt/tmp/makemkv/{{ item }}"
    state: directory
    owner: "{{local_user}}"
    group: "{{local_user}}"
    mode: "0755"
  loop:
    - oss
    - bin

- name: "install makemkv for linux build requirements"
  apt:
    state: latest
    name: "{{ mkv_pkgs }}"
  tags: 
    - apps
    - audioprod
  vars:
    mkv_pkgs:
      - build-essential 
      - pkg-config 
      - libc6-dev 
      - libssl-dev 
      - libexpat1-dev 
      - libavcodec-dev 
      - libgl1-mesa-dev 
      - qtbase5-dev 
      - zlib1g-dev

- name: "untar"
  unarchive:
    src: "https://www.makemkv.com/download/makemkv-{{ item }}-{{ makemkv_ver }}.tar.gz"
    dest: "/opt/tmp/makemkv/"
    remote_src: yes
  loop:
    - oss
    - bin

- name: "Create the ~/tmp directory for eula"
  ansible.builtin.file:
    path: "/opt/tmp/makemkv/makemkv-bin-{{ makemkv_ver }}/tmp"
    state: directory
    owner: "{{local_user}}"
    group: "{{local_user}}"
    mode: "0755"

- name: "touch the eula file"
  ansible.builtin.file:
    path: "/opt/tmp/makemkv/makemkv-bin-{{makemkv_ver }}/tmp/eula_accepted"
    state: directory
    owner: "{{local_user}}"
    group: "{{local_user}}"
    mode: "0755"

- name: "Run `install` target for bin as root"
  community.general.make:
    chdir: "/opt/tmp/makemkv/makemkv-bin-{{ makemkv_ver }}/"
    target: install
  become: yes

- name: "configure the build"
  shell:
    chdir: "/opt/tmp/makemkv/makemkv-{{ item }}-{{ makemkv_ver }}"
    cmd:   "/opt/tmp/makemkv/makemkv-{{ item }}-{{ makemkv_ver }}/configure"
  loop:
    - oss
  
- name: Build the default target
  community.general.make:
    chdir: "/opt/tmp/makemkv/makemkv-oss-{{ makemkv_ver }}"
    target: install

# - name: download the tarballs
#   get_url:
#     url: "https://www.makemkv.com/download/makemkv-{{item}}-{{makemkv_ver }}.tar.gz"
#     dest: /opt/tmp/
#     mode: '0644'
#   loop:
#     - oss
#     - bin
